name: Build Extension

on:
  push:
    branches:
      - main
    paths:
      - 'Extension-React/**'  # Only trigger on changes in Extension-React directory

jobs:
  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: Extension-React/package-lock.json

      - name: Build Project
        run: |
          cd Extension-React
          npm ci
          npm run build
          mv dist Syrup-dev
          cd Syrup-dev
          zip -r ../Syrup-dev.zip .

      - name: Delete old dev release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

      - name: Create Dev Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev
          name: "Development Build"
          body: |
            Latest development build from main branch
            Built from commit: ${{ github.sha }}
            
            ⚠️ This is a development build and may contain bugs.
          prerelease: true
          files: Extension-React/Syrup-dev.zip
          token: ${{ secrets.GITHUB_TOKEN }}